version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8001:8001"
    volumes:
      - ./:/var/www/auth
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites/:/etc/nginx/conf.d/
    networks:
      - msa-network


  #PHP Service
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SERVICE_NAME: auth
      SERVICE_TAGS: dev
    working_dir: /var/www/auth
    volumes:
      - ./:/var/www/auth
      - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - msa-network


  #MySQL Service
  auth_db:
    image: mysql:8.0
    container_name: auth_db
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: auth
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - .docker/data/dbdata:/var/lib/mysql
    #      - .docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
