---
apiVersion: v1
kind: Service
metadata:
  name: {service-name}-api
  namespace: {namespace}
spec:
  ports:
  - name: https
    port: 80
    protocol: TCP
    targetPort: 80
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: {service-name}-api
  type: ClusterIP
