version: "3.2"

services:

  redis:
    image: "redis:alpine"
    container_name: redis_api
    command: redis-server --requirepass root_pass
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis-data:/var/lib/redis
      - ./db-data/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      - network

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.19.0.1/24"
